---
to: <%= shortname %>-assets.bat.temp
sh: "echo rem DO NOT MODIFY! Automatically generated by CirnoJam-compile.bat at %DATE% - %TIME% >> <%= shortname %>-assets.bat && type <%= shortname %>-assets.bat.temp >> <%= shortname %>-assets.bat && rm <%= shortname %>-assets.bat.temp"
---
<% for (var i = 0; i < sprites.length; i++) { %>
echo Offsetting <%= sprites[i].name %>.png...
tools\setpng\setpng.exe -grab <%= sprites[i].offsets[0] %> <%= sprites[i].offsets[1] %> <%= shortname %>\<%= sprites[i].path %>\<%= sprites[i].name %>.png <%= shortname %>\<%= sprites[i].path %>\<%= sprites[i].name %>.png
<% } %>
